import type { Metadata } from "next";
import { Poppins, Red_Hat_Display } from "next/font/google";
import "./globals.css";

export const rhd = Red_Hat_Display({
  subsets: ["latin"],
  variable: "--font-rhd",
});

export const metadata: Metadata = {
  title: "deCube Modern Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rhd.className} antialiased overflow-x-hidden`}>
        {children}
      </body>
    </html>
  );
}
